language: ruby
# Start OSX builds before Linux, because they take longer.
os:
  - osx
  - linux
rvm: # http://rubies.travis-ci.org/
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0 # https://github.com/travis-ci/travis-ci/issues/7848
  - 2.5
matrix:
  exclude:
    - os: osx
      rvm: 1.9
    - os: osx
      rvm: 2.0
    - os: osx
      env: WITH_LIBXML=false V=1
  include:
    - name: test gumbo
      os: osx
      language: cpp
      install:
        - curl -L https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar zxf - --strip-components 1 -C gumbo-parser googletest-release-1.8.0/googletest
        - make -C gumbo-parser/googletest/make gtest_main.a
      before_script: true
      script:
        - make -C gumbo-parser
    - name: test gumbo
      os: linux
      language: cpp
      install:
        - curl -L https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar zxf - --strip-components 1 -C gumbo-parser googletest-release-1.8.0/googletest
        - make -C gumbo-parser/googletest/make gtest_main.a
      before_script: true
      script:
        - make -C gumbo-parser

env:
  - WITH_LIBXML=true V=1
  - WITH_LIBXML=false V=1
before_script:
  - if [ "$WITH_LIBXML" = "false" ]; then sudo apt-get remove libxml2-dev; fi
  - cd test && git clone --depth 1 --branch fix-noscript --single-branch https://github.com/stevecheckoway/html5lib-tests
sudo: required
cache: bundler
