language: ruby
rvm: # http://rubies.travis-ci.org/
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
env:
  - WITH_LIBXML=true
  - WITH_LIBXML=false
before_script: |
  if [ "$WITH_LIBXML" == "false" ]; then
    sudo apt-get remove libxml2-dev
  fi
