language: ruby
# Start OSX builds before Linux, because they take longer.
os:
  - osx
  - linux
rvm: # http://rubies.travis-ci.org/
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.0 # https://github.com/travis-ci/travis-ci/issues/7848
  - 2.5
env:
  - WITH_LIBXML=true
  - WITH_LIBXML=true NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - WITH_LIBXML=false
matrix:
  include:
    - name: test gumbo
      os: osx
      language: cpp
      install:
        - curl -L https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar zxf - --strip-components 1 -C gumbo-parser googletest-release-1.8.0/googletest
        - make -C gumbo-parser/googletest/make gtest_main.a
      before_script: true
      script:
        - make -C gumbo-parser
    - name: test gumbo
      os: linux
      language: cpp
      install:
        - curl -L https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar zxf - --strip-components 1 -C gumbo-parser googletest-release-1.8.0/googletest
        - make -C gumbo-parser/googletest/make gtest_main.a
      before_script: true
      script:
        - make -C gumbo-parser

before_script:
  - |
    if [ "$WITH_LIBXML" == "true" ]; then
      MAKE='make V=1' bundle exec rake compile -- --with-libxml2
    else
      MAKE='make V=1' bundle exec rake compile -- --without-libxml2
    fi
  - cd test && git clone --depth 1 --branch master --single-branch https://github.com/html5lib/html5lib-tests.git
script:
  - bundle exec rake
cache: bundler
